[package]
name = "bevy_grid"
version = "0.1.0"
authors = ["Thorge Hemken"]
edition = "2018"
license = "MIT"
description = "A plugin for the bevy game engine to add grids"

[dependencies]
bevy = "0.4"
